service: pro-series-serverless # NOTE: update this with your service name
frameworkVersion: "=1.38.0"
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs8.10
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:DeleteObject
        - s3:GetObject
      Resource:
         - Fn::Join:
           - ""
           - 
            - "arn:aws:s3:::"
            - Ref: PicturesBucket
            - "/*"
plugins:
  - serverless-stack-output
  - serverless-finch
  - serverless-single-page-app-plugin
  - serverless-webpack
  - serverless-dynamodb-autoscaling
  - serverless-s3-remover

custom:
  resourceNames: 
    # change this word to one of your choice, S3 public web buckets needs to be unique.
    # really... DON'T USE avocado
    uniqueWord: avocado
    uniqueStage: ${self:provider.stage}${self:custom.resourceNames.uniqueWord}
    frontEndBucket: ${self:custom.resourceNames.uniqueStage}-front-end 
    pictureBucket: ${self:custom.resourceNames.uniqueStage}-picture 
    pictureTable: ${self:custom.resourceNames.uniqueStage}-picture-table
    identityPool: ${self:custom.resourceNames.uniqueStage}IdentityPool
    userPool: ${self:custom.resourceNames.uniqueStage}-user-pool
    poolClient: ${self:custom.resourceNames.uniqueStage}-user-pool-client
  output:
    handler: scripts/config.handler # Same syntax as you already know
  capacities:
    - table: PicturesTable  # DynamoDB Resource
      read:
        minimum: 1        # Minimum read capacity
        maximum: 10     # Maximum read capacity
        usage: 0.75       # Targeted usage percentage
      write:
        minimum: 1       # Minimum write capacity
        maximum: 10      # Maximum write capacity
        usage: 0.5        # Targeted usage percentage
  client:
    bucketName: ${self:custom.resourceNames.frontEndBucket}
    distributionFolder: ../build 
    indexDocument: index.html
    errorDocument: index.html
  remover:
     buckets:
       - ${self:custom.resourceNames.frontEndBucket}
       - ${self:custom.resourceNames.pictureBucket}
# you can add packaging information here
# package:
#   include:
#      - src/test.jpg
#  exclude:
#    - exclude-me.js

functions: 
    dynamodb-trigger:
      name: trigger
      handler: src/trigger.handler 
      events:
        - stream:
            type: dynamodb
            batchSize: 1
            startingPosition: LATEST
            arn:
              Fn::GetAtt:
                - PicturesTable
                - StreamArn
      environment: 
        PICTURE_BUCKET: ${self:custom.resourceNames.pictureBucket}
    image-analysis:
      name: analysis
      handler: src/image.handler
      events:
        - http:
            path: image/analysis
            method: post     
            cors: true       
      environment: 
        PICTURE_BUCKET: ${self:custom.resourceNames.pictureBucket}
resources:
    - ${file(resources/security.yml)}
    - ${file(resources/data-storage.yml)}
    - ${file(resources/object-storage.yml)}
    - ${file(resources/misc.yml)}
