Resources:
  PicturesTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      TableName: ${self:custom.resourceNames.pictureTable}
      AttributeDefinitions:
        - 
          AttributeName: userId
          AttributeType: S
        - 
          AttributeName: pictureId
          AttributeType: S
      KeySchema:
        - 
          AttributeName: userId
          KeyType: HASH
        - 
          AttributeName: pictureId
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
Outputs:
  PicturesTableName:
    Value:
      Ref: PicturesTable