#############################################################################################
# This YML file declares the serverless stack's object storage related AWS resources.
#
# Author: Victor Santos Uceta
# License: Attribution-NonCommercial-NoDerivatives 4.0 International
#############################################################################################
Resources:
  # The definition of the front end S3 bucket which will host the web app. For more information on
  # S3 bucket as web app hosting read: https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html
  FrontEndBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.resourceNames.frontEndBucket}
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders: ['*']
          AllowedMethods: [GET,HEAD]
          AllowedOrigins: ['*']
          ExposedHeaders: [Date]
  # Definition of the Picture's storage bucket. For more information about S3 buckets
  # read: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html
  PicturesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.resourceNames.pictureBucket}
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders: ['*']
          AllowedMethods: [GET,PUT,POST,DELETE,HEAD]
          AllowedOrigins: ['*']
          ExposedHeaders: [Date]
      # LifecycleConfiguration:
      #   Rules:
      #     - Id: deleteEverythingInOneDay
      #       Prefix: ''
      #       Status: Enabled
      #       ExpirationInDays: 1
# when the stack is sucessfully build, it will print the following variables. Which
# correspond to properties of the created resources. This properties will be used
# as environment variable via a .env file.
Outputs:
  FrontEndBucketName:
    Value:
      Ref: FrontEndBucket
  PicturesBucketName:
    Value:
      Ref: PicturesBucket