Resources:
  FrontEndBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.resourceNames.frontEndBucket}
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders: ['*']
          AllowedMethods: [GET,HEAD]
          AllowedOrigins: ['*']
          ExposedHeaders: [Date]
  PicturesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ${self:custom.resourceNames.pictureBucket}
      CorsConfiguration:
        CorsRules:
        - AllowedHeaders: ['*']
          AllowedMethods: [GET,PUT,POST,DELETE,HEAD]
          AllowedOrigins: ['*']
          ExposedHeaders: [Date]
Outputs:
  FrontEndBucketName:
    Value:
      Ref: FrontEndBucket
  PicturesBucketName:
    Value:
      Ref: PicturesBucket